### ISSUE TITLE
Loading react and multiple dependencies to the front end of a site

### ISSUE THREAD

**Issue by timnashcouk** [wholesomecode/wholesome-publishing#23]
I noticed a significant slowdown on my site while testing the plugin and located the issue, every page is now loading a full copy of React along with dozens of dependencies, extra markup to user-facing pages.

```
<script type='text/javascript' src='//cdn.timnash.co.uk/wp/wp-includes/js/dist/vendor/react.min.js?ver=16.9.0'></script>
--
  | <script type='text/javascript' src='//cdn.timnash.co.uk/wp/wp-includes/js/dist/i18n.min.js?ver=cced130522e86c87a37cd7b8397b882c'></script>
  | <script type='text/javascript' src='//cdn.timnash.co.uk/wp/wp-includes/js/dist/vendor/lodash.min.js?ver=4.17.15'></script>
```
 This results in significant extra load and serious performance issues, in my case causing a 6sec increase on load time of my home page.

![Screenshot 2020-07-11 at 06 07 53](https://user-images.githubusercontent.com/5869812/87217041-11f65880-c33d-11ea-8ec7-76e3e8bfaec3.png)
![Screenshot 2020-07-11 at 06 08 29](https://user-images.githubusercontent.com/5869812/87217040-115dc200-c33d-11ea-8093-1aea5cd6c04e.png)

**Expected behaviour:**
I don't believe there is a need to be loading react or any of the dependencies to the front end, non-user facing aspects of the site.

**Steps to reproduce the bug**
- enable the plugin
- view source of page.

**Comment by mattwatsoncodes** [comment]
Cheers @timnashcouk, let me look into this. There must be an issue with my enqueues.

**Comment by mattwatsoncodes** [comment]
Fixed @timnashcouk I'll be rolling out this afternoon along with the email notifications I've been working on.
